### ISSUE TITLE
Font spacing is wrong for Roboto. 

### ISSUE THREAD

**Issue by shaik41** [a3ammar/roto-kufi-arabic#1]
I guess you merged using Font Face which screws the line spaces

**Comment by a3ammar** [comment]
Can you show me a screenhost? I merged the fonts using fontforge, I guess you could achieve the same results using `unicode-range` in `@font-face` but then you'll have to provide both font files.

**Comment by shaik41** [comment]
You can see this on font forge itself. Just open regular robot and noto+roboto. You will see english [Latin glyph) has more character spacing.
